-- USERS TABLE

CREATE TABLE USERS (
                       ID NUMBER PRIMARY KEY,
                       NAME VARCHAR2(100) NOT NULL,
                       EMAIL VARCHAR2(150) UNIQUE NOT NULL,
                       PASSWORD VARCHAR2(256) NOT NULL,
                       ROLE VARCHAR2(20) CHECK (ROLE IN ('JOB_SEEKER', 'EMPLOYER')),
                       PHONE VARCHAR2(20),
                       SECURITY_QUESTION VARCHAR2(255),
                       SECURITY_ANSWER VARCHAR2(255),
                       PROFILE_COMPLETE NUMBER(1) DEFAULT 0,
                       CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- RESUMES TABLE

CREATE TABLE RESUMES (
                         ID NUMBER PRIMARY KEY,
                         USER_ID NUMBER UNIQUE,
                         OBJECTIVE CLOB,
                         EDUCATION CLOB,
                         EXPERIENCE CLOB,
                         SKILLS CLOB,
                         PROJECTS CLOB,
                         UPDATED_AT DATE DEFAULT SYSDATE,
                         CONSTRAINT FK_RESUME_USER FOREIGN KEY (USER_ID)
                             REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE RESUMES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER RESUMES_TRG
BEFORE INSERT ON RESUMES
FOR EACH ROW
BEGIN
SELECT RESUMES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- JOBS TABLE

CREATE TABLE JOBS (
                      ID NUMBER PRIMARY KEY,
                      EMPLOYER_ID NUMBER,
                      TITLE VARCHAR2(150) NOT NULL,
                      DESCRIPTION CLOB,
                      SKILLS VARCHAR2(255),
                      EXPERIENCE_YEARS NUMBER,
                      EDUCATION VARCHAR2(255),
                      LOCATION VARCHAR2(100),
                      SALARY_MIN NUMBER,
                      SALARY_MAX NUMBER,
                      JOB_TYPE VARCHAR2(50),
                      DEADLINE DATE,
                      STATUS VARCHAR2(20) DEFAULT 'OPEN',
                      CONSTRAINT FK_JOB_EMPLOYER FOREIGN KEY (EMPLOYER_ID)
                          REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE JOBS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER JOBS_TRG
BEFORE INSERT ON JOBS
FOR EACH ROW
BEGIN
SELECT JOBS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- APPLICATIONS TABLE

CREATE TABLE APPLICATIONS (
                              ID NUMBER PRIMARY KEY,
                              JOB_ID NUMBER,
                              SEEKER_ID NUMBER,
                              RESUME_ID NUMBER,
                              COVER_LETTER CLOB,
                              STATUS VARCHAR2(20) DEFAULT 'APPLIED',
                              APPLIED_DATE DATE DEFAULT SYSDATE,
                              WITHDRAWN_REASON VARCHAR2(255),
                              CONSTRAINT FK_APP_JOB FOREIGN KEY (JOB_ID)
                                  REFERENCES JOBS(ID) ON DELETE CASCADE,
                              CONSTRAINT FK_APP_USER FOREIGN KEY (SEEKER_ID)
                                  REFERENCES USERS(ID) ON DELETE CASCADE,
                              CONSTRAINT FK_APP_RESUME FOREIGN KEY (RESUME_ID)
                                  REFERENCES RESUMES(ID)
);

CREATE SEQUENCE APPLICATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER APPLICATIONS_TRG
BEFORE INSERT ON APPLICATIONS
FOR EACH ROW
BEGIN
SELECT APPLICATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


-- NOTIFICATIONS TABLE

CREATE TABLE NOTIFICATIONS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER,
                               MESSAGE VARCHAR2(500),
                               IS_READ NUMBER(1) DEFAULT 0,
                               CREATED_AT DATE DEFAULT SYSDATE,
                               CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID)
                                   REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE NOTIFICATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NOTIFICATIONS_TRG
BEFORE INSERT ON NOTIFICATIONS
FOR EACH ROW
BEGIN
SELECT NOTIFICATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
